### ISSUE TITLE
Why is there no simuvex.whl in this?

### ISSUE THREAD

**Issue by spwpun** [andreafioraldi/angr-win64-wheels#1]
And after I using pip to install simuvex, it comes to this error when I import simuvex:
```
>>> import simuvex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "simuvex\__init__.py", line 11, in <module>
    from .s_state import SimState
  File "simuvex\s_state.py", line 25, in <module>
    from .plugins import default_plugins
  File "simuvex\plugins\__init__.py", line 16, in <module>
    from .unicorn_engine import Unicorn
  File "simuvex\plugins\unicorn_engine.py", line 1290, in <module>
    from ..engines.vex import ccall
  File "simuvex\engines\__init__.py", line 4, in <module>
    from .vex import SimEngineVEX
  File "simuvex\engines\vex\__init__.py", line 32, in <module>
    from .expressions import SimIRExpr, translate_expr
  File "simuvex\engines\vex\expressions\__init__.py", line 30, in <module>
    from .op import SimIRExpr_Unop, SimIRExpr_Binop, SimIRExpr_Triop, SimIRExpr_Qop
  File "simuvex\engines\vex\expressions\op.py", line 5, in <module>
    from ..irop import translate
  File "simuvex\engines\vex\irop.py", line 73, in <module>
    all_operations = pyvex.enum_IROp_fromstr.keys()
AttributeError: 'module' object has no attribute 'enum_IROp_fromstr'
```
I tried different versions of simuvex, but it didn't work. Or what's the specific version number of simuvex which can use in angr-7.8.7.1?
Thanks applying.

**Comment by spwpun** [comment]
It seems that simuvex has been DEPRECATED from version 7.7.9.8，it's my fault.:(
